Structure and routes
sagieramos/soccerhub pull request #1
Opened 2023-10-11 19:02 UTC by sagieramos

### Key Features 
- The project is a single-page application (SPA) built with React and Redux.
- The data retrieved from the [API](https://api-football-standings.azharimm.dev/) is stored in the Redux store.
- Each page has a unique route

## [Live Demo](https://soccerhub.onrender.com/)

2023-10-11 19:19 UTC, DeliceLydia requested changes
## Hi @sagieramos, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## Suggested changes
_Check the comments under the review._



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-10-11 19:19 UTC, DeliceLydia commented on README.md
> +- [Live Demo](https://soccerhub.onrender.com/)
- [ ] Please add in the README a recorded video presenting
- The features of the project
- A piece of the code you find interesting or proud of making

2023-10-12 09:52 UTC, Ibizugbe requested changes
Hi @sagieramos 👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/sagieramos/soccerhub/assets/64643995/4c7886d0-a388-445f-95c8-7033166e4046)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅✅

- [x] Video presentation looks good👍🏼.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 09:52 UTC, Ibizugbe commented on README.md
Nice job so far, your video presentation looks good👍🏼. In a bit to implement the corrections from the previous reviewer, I noticed you replaced the Live demo link with the video presentation. Kindly note that it is also a requirement that your readme file has a live demo link (A link to your deployed project) just as it should have a video presentation link. Kindly Add the link to your deployed project in your live demo link. Add a section called video presentation and add the link to your video presentation.

2023-10-12 10:22 UTC, topeogunleye approved these changes
### Hi @sagieramos, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. I'm pleased to announce that you've addressed all the concerns. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 

### Video Presentation and Live Demo Link: 🎥🔗
- Fantastic job ensuring that both the "Live Demo" and the "Video Presentation" links are present in your README. The clear distinction between the two links provides clarity for anyone viewing your project repository. Well done! 👏

### Overall: 🏆
Your attentiveness to feedback and swiftness in making the necessary adjustments is truly commendable. It's evident that you're dedicated to delivering quality work. 

With these changes, your project meets the required standards. Keep up this momentum in your coding journey!

Should you have any further questions, concerns, or need clarifications, don't hesitate to reach out. Remember, continuous improvement is key!

Warm regards and congratulations on this milestone! 🎉🚀
 
## [Optional] suggestions:
- For future pull requests, please notice that your branch name `structure-and-routes` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-structure-and-routes`. This makes it easier to track the changes and the purpose of each branch. 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 13:33 UTC, merged